#!/usr/bin/env python3.4

from argparse import ArgumentParser
from lib.EvolutronicLife import EvolutronicLife


if __name__ == "__main__":
    parser = ArgumentParser(description='Evolutronic Life')
    parser.add_argument(
        '-m', '--map', default='map1', choices=['map1'],
        help='The map with which to start the simulation'
    )
    args = parser.parse_args()
    
    EvolutronicLife(args.map).run()
