#!/usr/bin/env python3.4

from os import listdir
from argparse import ArgumentParser
from lib.EvolutronicLife import EvolutronicLife


if __name__ == "__main__":
    maps = [file[:-4] for file in listdir('./maps') if file.endswith('.map')]
    parser = ArgumentParser(description='Evolutronic Life')
    parser.add_argument(
        '-m', '--map', default='map1', choices=maps,
        help='The map with which to start the simulation'
    )
    args = parser.parse_args()
    
    EvolutronicLife(args.map)#.run()
