#!/usr/bin/env python3.4

from sys import path
path.append('lib')  #add lib folder to module search path
from os import listdir
from argparse import ArgumentParser
import EvolutronicLife as EvoLife


if __name__ == "__main__":
    maps = [file[:-4] for file in listdir('./maps') if file.endswith('.map')]
    parser = ArgumentParser(description='Evolutronic Life')
    parser.add_argument(
        '-m', '--map', default='map1', choices=maps,
        help='The map with which to start the simulation'
    )
    parser.add_argument(
        '-k', '--kickstart', default=1, type=int,
        help='Specify the starting step. The preceding steps are executed hidden'
    )
    args = parser.parse_args()

    EvoLife.run(args.map, args.kickstart)